apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: categorisation-tool
 namespace: categorisation-tool-preprod
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/whitelist-source-range: "62.25.109.197/32,195.92.38.16/28,81.134.202.29/32,217.33.148.208/29"
spec:
  rules:
  - host: categorisation-tool-preprod.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: categorisation-tool-svc
          servicePort: 3000
