apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: categorisation-tool
 namespace: categorisation-tool-dev
 annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: categorisation-tool-dev.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: categorisation-tool-svc
          servicePort: 3000
