apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: categorisation-tool
  labels:
    app: categorisation-tool
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: categorisation-tool
  template:
    metadata:
      labels:
        app: categorisation-tool
    spec:
      containers:
        - name: categorisation-tool
          image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/omic/categorisation-tool:latest
          imagePullPolicy: Always
          # command: ['sh', '-c', "bundle exec puma -p 3000 -C ./config/puma_prod.rb --pidfile /tmp/server.pid"]
          ports:
            - containerPort: 3000
          env:
            - name: NOMIS_OAUTH_PUBLIC_KEY
              value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6Y3g3WWJ3MkJBV3Y3U3NFSVVHUAppeUpTSURndHFCeDE5VHdtN3VJM1RYNXpSY3JabFV4Y0VtUEpHVWd5K0QySkloVmxxbWVxd0dWMkNOT3FaQmdHCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4KcU9HWmM4dXBOK3c1ZFpyTnYrMkdMZ3hLMnBldE1VL0JoWWVXZjNLdllJTzE2djF1dm5GT0dPMTNIb1d1NUJ0ZApTdC9UZ2NsRmhWTEVkR3c3WGJpWUhuTlpJZGh3YU5RaVlnbVhtalpWZE15Q1BETW8xMExrVjFwM1V5MTVwTU14ClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8KbHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
            - name: NOMIS_AUTH_EXTERNAL_URL
              value: "https://gateway.t3.nomis-api.hmpps.dsd.io/auth/"
            - name: INGRESS_HOST
              value: "categorisation-tool.apps.cloud-platform-live-0.k8s.integration.dsd.io"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-dev
                  key: database_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-dev
                  key: database_username
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-dev
                  key: rds_instance_address
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: categorisation-tool-rds-dev
                  key: database_name
            - name: API_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: categorisation-tool-secrets
                    key: api_client_id
            - name: API_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: categorisation-tool-secrets
                    key: api_client_secret
